spring.application.name=hr-erp-isapi

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hr_erp_isapi}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:ping4}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=8081

isapi.alertStream.disconnectBackoffBaseSeconds=3
isapi.alertStream.deployExceedMaxBackoffSeconds=300

acs.history.major=${ACS_HISTORY_MAJOR:5}
acs.history.minor=${ACS_HISTORY_MINOR:75}
